import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer/Footer";
import { serverFirestore } from "./config/firebase.server.config";
import Header from "./components/Header";
import { DocumentData } from "firebase-admin/firestore";
import { clearUserData, getAppData, getUserData } from "./utils/utils";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const appData = await getAppData();
  let user: DocumentData | null | undefined = null;
  try {
    user = await getUserData();
  } catch (error: any) {
    console.log("Home:", error ?? "Something is wrong!");
  }

  return (
    <html lang="en" data-theme="light">
      <head>
        <script src="http://localhost:8097"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Header appData={appData} user={user} />

        <main className="flex-grow">{children}</main>

        <Footer appData={appData} user={user} />
      </body>
    </html>
  );
}
